language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS

    # The SDK version used to compile your project
    - android-$ANDROID_API

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-$ANDROID_API
    - sys-img-armeabi-v7a-android-20

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
  - yes | sdkmanager "platforms;android-27"
  - chmod +x gradlew

cache:
  directories:
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
