language: android
sudo: false
android:
  components:
    # The BuildTools version used by your project
    - tools
    - build-tools-28.0.0
    - platform-tools

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-28

    # The SDK version used to compile your project
    - android-28

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

os:
  - linux
